
from . import property_type
from . import property_land_use
from . import property_availability
from . import property_status
from . import commission_share
from . import property_development
from . import property_business_unit
from . import property_development_type
from . import res_municipality
from . import res_colony
from . import property_smoking
from . import property_payment_method
from . import property_invoice
from . import property_giro
from . import property_deposit
from . import property_term
from . import property_customer_profile
from . import property_type_training
from . import property_exclusive_time
from . import property_commission
from . import property_commission_type
from . import verticali_property
from . import property_fields
from . import property_contracts
from . import res_country_state
from . import crm_lead
from . import commission_type
from . import res_zipcode
from . import res_property